- CONTRIBUTING.md
- LICENSE
- README.md
CONTRIBUTING.md was a duplicate and updated year in licence and charts URL
> remove duplicate and updated URL and year

- charts/chronograf/Chart.yaml
- charts/influxdb/Chart.yaml
- charts/kapacitor/Chart.yaml
- charts/telegraf/Chart.yaml
This is required by chart-testing.
> Use github handles instead of real names.

- charts/chronograf/Chart.yaml
- charts/chronograf/templates/deployment.yaml
- charts/influxdb/Chart.yaml
- charts/kapacitor/Chart.yaml
- charts/telegraf/Chart.yaml
To fix Release Charts workflow since charts were not bumped on #7
> Version bump all charts

- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
- charts/influxdb/templates/backup-cronjob.yaml
Add Backup/Restore section to README, minor tweaks to backup cronjob.
> [influxdb] Backup restore readme

- charts/influxdb/Chart.yaml
- charts/influxdb/templates/statefulset.yaml
It appears that 8088 is blocked unless you have enterprise set.
> 19 port 8088 is blocked

- README.md
- charts/chronograf/Chart.yaml
- charts/chronograf/README.md
- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
- charts/kapacitor/Chart.yaml
- charts/kapacitor/README.md
- charts/kapacitor/values.yaml
- charts/telegraf/Chart.yaml
- charts/telegraf/README.md
> Fix reference to stable/* for influxdata/*

- README.md
- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
adding the config param table in the repo's README.md
> [add-config-param-table] add config param table in README.md

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/README.md
* Improve documentation 
* fix some helm commands to be compatible with helm 3
> [telegraf-ds] Improve documentation

- charts/chronograf/Chart.yaml
- charts/chronograf/README.md
- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
- charts/kapacitor/Chart.yaml
- charts/kapacitor/README.md
- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/README.md
- charts/telegraf/Chart.yaml
- charts/telegraf/README.md
* all charts to use `helm upgrade --install` instead of `helm install`
* `helm delete --purge` replaced by `helm uninstall`
> Use of helm upgrade --install and helm uninstall

- charts/chronograf/Chart.yaml
- charts/chronograf/values.yaml
- charts/influxdb/Chart.yaml
- charts/influxdb/values.yaml
I had these warnings when in a chart a field had null as default value and in the values it was substituted with a map. Changing null to empty map {} eliminated the warning.
> Add {} to prevent warning in Helm3

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/values.yaml
- charts/telegraf/Chart.yaml
- charts/telegraf/README.md
- charts/telegraf/values.yaml
Upgrade telegraf version to 1.14 for both charts
> Upgrade telegraf to 1.14 for telegraf & telegraf-ds charts

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/templates/_helpers.tpl
- charts/telegraf-ds/templates/role.yaml
> fix: add nodes/proxy permission for kubelet pod request

- charts/telegraf-ds/Chart.yaml
- charts/telegraf/Chart.yaml
- charts/telegraf/README.md
- charts/telegraf/templates/configmap.yaml
- charts/telegraf/templates/service.yaml
- charts/telegraf/values.yaml
* Fix livenessProbe, readynessProbe and health service
* remove @naseemkullah from telegraf(-ds) maintainers list as requested on slack
> Fix telegraf health check with internal plugin enabled

- charts/telegraf/Chart.yaml
- charts/telegraf/templates/NOTES.txt
(Also bump version to 1.7.12.)
> Edit telegraf post-install note

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/README.md
- charts/telegraf-ds/templates/_helpers.tpl
- charts/telegraf-ds/templates/configmap.yaml
- charts/telegraf-ds/values.yaml
> Adding a flag to enable inputs internal plugin

- charts/chronograf/Chart.yaml
- charts/chronograf/values.yaml
> align variable name (#103)

- charts/telegraf-operator/Chart.yaml
- charts/telegraf-operator/templates/certificate.yml
- charts/telegraf-operator/templates/mutatingwebhookconfiguration.yml
- charts/telegraf-operator/values.yaml
also bumping telegraf-operator version and adjusting resources
> fixing certificate name and configuration when using cert-manager

- charts/influxdb/Chart.yaml
- charts/influxdb/templates/backup-pvc.yaml
reference to the value is out of order. Supposed to be backup.persistence.
> Typo in template

- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
> [influxdb] Changed auth_enabled to auth-enabled

- charts/influxdb-enterprise/Chart.yaml
- charts/influxdb-enterprise/templates/data-service.yaml
- charts/influxdb-enterprise/templates/data-statefulset.yaml
> fix: use correct port definitions

- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
- charts/influxdb/templates/service.yaml
- charts/influxdb/values.yaml
Signed-off-by: Ryan Holt <ryan@ryanholt.net>
> enable support for externalIPs, externalTrafficPolicy

- charts/influxdb-enterprise/Chart.yaml
- charts/influxdb-enterprise/templates/data-configmap.yaml
- charts/influxdb-enterprise/values.yaml
> chore: remove verbose curl logging

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/templates/daemonset.yaml
Also adds the ability to set `nodeSelector`.
Fixes #166
> Add support for affinity to telegraf-ds

- charts/influxdb-enterprise/Chart.yaml
Updating maintainers of enterprise templates to reflect changes
> chore:update maintainers

- charts/influxdb2/Chart.yaml
- charts/influxdb2/templates/job-setup-admin.yaml
Fixes https://github.com/influxdata/helm-charts/issues/175
Signed-off-by: Andrew Suderman <andrew@sudermanjr.com>
> [influxdb2] Fix helm hook annotations

- charts/telegraf-operator/Chart.yaml
- charts/telegraf-operator/templates/_helpers.tpl
Currently generated certificate doesn't match with the the service name
> Use fullname template for certificate name

- charts/influxdb-enterprise/Chart.yaml
- charts/influxdb-enterprise/templates/data-service.yaml
- charts/influxdb-enterprise/values.yaml
> feat(influxdb-enterprise): add nodeport service

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/values.yaml
- charts/telegraf/Chart.yaml
- charts/telegraf/values.yaml
Update `telegraf` & `telegraf-ds` charts to use telegraf 1.15 (instead of 1.14)
> feat(telegraf, telegraf-ds): upgrade image to 1.15

- charts/influxdb-enterprise/Chart.yaml
- charts/influxdb-enterprise/templates/data-configmap.yaml
> fix: put end statement in correct location to separate auth and tls

- charts/influxdb2/Chart.yaml
- charts/influxdb2/templates/service.yaml
> chore: version bump

- charts/telegraf-operator/Chart.yaml
Fixes issue reported in https://github.com/influxdata/helm-charts/pull/216#issuecomment-708992376
> fix(telegraf-operator): update version of telegraf-operator image

- charts/chronograf/Chart.yaml
- charts/chronograf/templates/deployment.yaml
- charts/chronograf/values.yaml
Adding support for additional volumes/volumeMounts in Chronograf
**Reason:**
Adds a ssl certificate that we need in order to connect to an external influxdb
> added volumes for chronograf.

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/values.yaml
- charts/telegraf/Chart.yaml
- charts/telegraf/values.yaml
Upgrade telegraf to 1.16 release.
> chore: bump telegraf to 1.16

- charts/chronograf/Chart.yaml
- charts/chronograf/templates/deployment.yaml
- charts/chronograf/values.yaml
useful when having a pvc attached
> allow using recreate when updating deployment

- charts/telegraf/Chart.yaml
- charts/telegraf/templates/configmap.yaml
> Reorder conditional end to allow inputs to render

- charts/chronograf/Chart.yaml
- charts/chronograf/templates/deployment.yaml
A typo prevents .Values.volumes from working correctly.  Indentation was also incorrect.
Steps to reproduce:
Install chronograf with the volumes value set
> [Chronograf] Fix: volume attachment does not work

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/values.yaml
- charts/telegraf/Chart.yaml
- charts/telegraf/values.yaml
> chore: bump telegraf image to 1.17

- charts/influxdb/Chart.yaml
- charts/influxdb/templates/ingress.yaml
- charts/influxdb/values.yaml
More info here: https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
> Adding support for Kubernetes 1.8 ingressClassName

- charts/kapacitor/Chart.yaml
- charts/kapacitor/values.yaml
awaiting DockerHub merge: https://github.com/docker-library/official-images/pull/9938
> Update to Kapacitor 1.5.9

- charts/influxdb-enterprise/Chart.yaml
- charts/influxdb-enterprise/values.yaml
Updating Chart config to track the latest release 1.8.5.
> update enterprise version to latest release

- charts/telegraf-operator/Chart.yaml
- charts/telegraf-operator/templates/_helpers.tpl
- charts/telegraf-operator/templates/clusterrolebinding.yml
- charts/telegraf-operator/templates/mutatingwebhookconfiguration.yml
Addition to fixes in https://github.com/influxdata/telegraf-operator/issues/53
> [telegraf-operator] Fix deprecation warnings

- charts/telegraf/Chart.yaml
- charts/telegraf/templates/_helpers.tpl
Fix the configmap templating for processor plugins:
- Converter
- Clone
- Override
https://docs.influxdata.com/telegraf/v1.14/plugins/plugin-list/#clone
Input values for tests:
```
config:
processors:
- enum:
mapping:
field: "status"
dest: "status_code"
value_mappings:
healthy: 1
problem: 2
critical: 3
- converter:
tags:
measurement: []
string: []
integer: []
unsigned: []
boolean: []
float: []
fields:
measurement: []
tag: []
string: []
integer: []
unsigned: []
boolean: []
float: []
- clone:
name_override: "new_name"
name_prefix: "new_name_prefix"
name_suffix: "new_name_suffix"
tags:
additional_tag: "tag_value"
- override:
name_override: "new_name"
name_prefix: "new_name_prefix"
name_suffix: "new_name_suffix"
tags:
additional_tag: "tag_value"
```         
Results:
```
[[processors.enum]] …
```
> Fix - Issue #307

- charts/influxdb/Chart.yaml
- charts/influxdb/values.yaml
> Shift to InfluxDB OSS 1.8.6

- charts/telegraf/Chart.yaml
- charts/telegraf/templates/_helpers.tpl
Resolves #375. Tested locally with input from linked issue.
> [telegraf] Fix tagpass and tagdrop in aggregations

- .github/workflows/helm-charts-release.yaml
- .github/workflows/helm-charts-test.yaml
- releaser 1.0.0-rc.1 -> 1.2.1
- Helm installation via action (the same as in tests)
> chore: update chart releaser action and Helm installation

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/values.yaml
- charts/telegraf/Chart.yaml
- charts/telegraf/values.yaml
update telegraf and telegraf-ds versions
> chore: update telegraf versions

- README.md
We need to provide more direct guidance on support provided for these charts/this repo.
@derektamsen and @mhall119 I'd appreciate a look to see if the language here makes sense.
> Clarify support options

- charts/influxdb/Chart.yaml
- charts/influxdb/templates/statefulset.yaml
Why:
* Labels defined as podLabels in values do not get added to pods
How:
* Add podLabels to StatefulSet template
Tests:
```
$ cat /tmp/influx-values.yml
podLabels:
influx/testlabel: testvalue
$ git --no-pager log --oneline -1
847f9a6 (HEAD -> influxdb-chart-utilize-pod-labels, tag: influxdb-4.10.0, upstream/master, origin/master, origin/HEAD, master) fix: tag conflicts existed, bumping version
$ git --no-pager diff upstream/master
$ helm install test-influxdb charts/influxdb --values /tmp/influx-values.yml > /dev/null
$ k get pods test-influxdb-0 -o json | jq '.metadata.labels'
{
"app.kubernetes.io/instance": "test-influxdb",
"app.kubernetes.io/name": "influxdb",
"controller-revision-hash": "test-influxdb-866c48867f",
"statefulset.kubernetes.io/pod-name": "test-influxdb-0"
}
$ helm …
```
> Add podLabels to influxdb's StatefulSet

- charts/influxdb2/Chart.yaml
- charts/influxdb2/templates/statefulset.yaml
- charts/influxdb2/values.yaml
> Add subPath value to influxdb2

- charts/chronograf/Chart.yaml
- charts/chronograf/templates/ingress.yaml
- charts/chronograf/values.yaml
> add className for chronograf

- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
- charts/influxdb/templates/backup-cronjob.yaml
- charts/influxdb/values.yaml
> fix Azure image and InfluxDB version refs

- charts/influxdb2/Chart.yaml
- charts/influxdb2/templates/NOTES.txt
- charts/influxdb2/templates/_helpers.tpl
- charts/influxdb2/templates/serviceaccount.yaml
- charts/influxdb2/templates/statefulset.yaml
- charts/influxdb2/values.yaml
- adds service account
Closes #428
- adds note about admin password persistence
Closes #322
> [influxdb2] add service account

- charts/kapacitor/Chart.yaml
- charts/kapacitor/templates/rolebinding.yaml
Also, bump chart's version accordingly.
Did not find `CHANGELOG.md` though.
> Remove duplicate roleRef (#431)

- charts/influxdb-enterprise/Chart.yaml
- charts/influxdb-enterprise/templates/data-configmap.yaml
- charts/influxdb-enterprise/values.yaml
Enabling Flux in InfluxDB Enterprise.
> feat(enable-flux): add flux-enabled property

- charts/influxdb2/Chart.yaml
- charts/influxdb2/values.yaml
It doesn't match with the template
> fix(influxdb): ingress property className

- charts/kapacitor/Chart.yaml
- charts/kapacitor/README.md
- charts/kapacitor/templates/deployment.yaml
- charts/kapacitor/values.yaml
Closes #276 _changes copy pasted from #143_
Closes #330  (README only fix)
> [kapacitor] add affinity and tolerations

- charts/chronograf/Chart.yaml
- charts/chronograf/templates/_helpers.tpl
- charts/chronograf/templates/deployment.yaml
- charts/chronograf/templates/ingress.yaml
- charts/chronograf/templates/pvc.yaml
- charts/chronograf/templates/secret.yaml
- charts/chronograf/templates/service.yaml
- charts/chronograf/values.yaml
> [chronograf] add recommended labels and startupProbe

- charts/telegraf-ds/Chart.yaml
- charts/telegraf-ds/templates/daemonset.yaml
- charts/telegraf-ds/values.yaml
Ported from `telegraf` chart.
Closes #359.
> [telegraf-ds] add custom volumes and mountPoints support

- charts/influxdb/Chart.yaml
- charts/influxdb/README.md
- charts/influxdb/templates/service.yaml
- charts/influxdb/values.yaml
> Add service.nodePorts.http parameter to configure NodePort

- charts/telegraf-operator/Chart.yaml
Bumping the version of telegraf operator after releasing https://github.com/influxdata/telegraf-operator/pull/108 this feature
> Update telegraf-operator to 1.3.10

- charts/influxdb2/Chart.yaml
- charts/influxdb2/templates/statefulset.yaml
- charts/influxdb2/values.yaml
@rawkode I added the missing imagePullSecrets. Would be happy if someone could take a look on this
> Add image pull secret to influxdb2 chart

- charts/influxdb-enterprise/Chart.yaml
Rebasing from earlier PR. This updates the Enterprise version to the latest 1.10 release.
> updates Enterprise chart to latest version

- charts/telegraf-ds/Chart.yaml
- charts/telegraf/Chart.yaml
> chore: update Telegraf versions for v1.24.3

- charts/telegraf-operator/Chart.yaml
- charts/telegraf-operator/templates/deployment.yaml
- charts/telegraf-operator/values.yaml
- add support for disabling the flag --enable-default-internal-plugin
> feat: [telegraf-operator] add support for disabling the flag --enable-default-internal-plugin

- charts/influxdb3-clustered/Chart.yaml
- charts/influxdb3-clustered/values.yaml
[`0.0.15`](https://github.com/kubecfg/kubit/releases/tag/v0.0.15) was released a few weeks ago :rocket:
> chore(clustered): bump kubit to 0.0.15

- charts/influxdb3-clustered/Chart.yaml
Update Clustered helm chart to latest release version
> chore: updated clustered app version

- charts/influxdb3-clustered/Chart.yaml
Updates the helm chart for the `20250613-1754010` release
> feat: update chart for 20250613-1754010 release

- charts/influxdb3-clustered/Chart.yaml
- charts/influxdb3-clustered/templates/app-instance.yml
- charts/influxdb3-clustered/values.yaml
Hi, I wanted to add the ability to pause the kubit operator from the helm chart.
> feat: add the ability to pause kubit operator in appinstance template

- charts/telegraf-ds/Chart.yaml
- charts/telegraf/Chart.yaml
> chore: update Telegraf versions for v1.35.1

- charts/telegraf-ds/Chart.yaml
- charts/telegraf/Chart.yaml
> chore: update Telegraf versions for v1.35.2

- charts/influxdb3-clustered/Chart.yaml
Update helm chart for 20250721-1796368 clustered release
> chore: update chart for 20250721 release
