charts/telegraf/Chart.yaml
charts/telegraf/templates/_helpers.tpl
charts/telegraf/templates/configmap.yaml

- Fix an error that template get wrong length of elements
- Fix an error that uncontrollable orders of map make the toml wrong. i.e.
Yaml
```yaml
- d:
b
c
a:
- x
- y 
```
Current TOML
```toml
[d]
[a]
x
y
b
c
```
Expected
```toml
[d]
b
c
[a]
x
y
```
- Add aggregators supported

Update template parser

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/post-install-set-auth.yaml
charts/influxdb/values.yaml

This PR adds to variables for configuration of the post install auth job. This is to help in scenarios where the installation is taking longer but will eventually finish if given more time. 
Both of the variables default to either the previous value or the kubernetes default value.

Auth job variables

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/configmap.yaml

Provided that int values can be quoted in the config, this fixes the issue where strings are not quoted in the rendered config.
e.g. the value:
```
config:
http:
max_row_limit: 0
logging:
format: json
```
renders in the configmap, prior to this commit:
```
[http]
max_row_limit = 0
[...]
[logging]
format = json
```
Which results in the following error: `run: parse config: Near line 43 (last key parsed 'logging.format'): expected value but found "json" instead`
While this commit renders:
```
[http]
max_row_limit = "0"
[...]
[logging]
format = "json"
```
which produces no error.

[influxdb] Fix config rendering.

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/_helpers.tpl

The current implementation produces an invalid TOML when using tags in inputs. 
Example:
```yaml
- http_response:
address: https://foobar.com/healthz
tags:
team: a-team
```
Produces:
```
[[inputs.http_response]]
address = "https://foobar.com/healthz"
[[inputs.http_response.tags]]
team = a-team
```

Adds missing quote

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/configmap.yaml

My influxdb `config` object contains some boolean values which was causing this error to be thrown:
```sh
run: parse config: toml: cannot load TOML value of type string into a Go boolean
```
The influxdb configuration requires boolean values to not be quoted and strings to be quoted. With the type check update, a resulting config snippet as follows:
```toml
[http]
auth-enabled = true
bind-address = ":8086"
bind-socket = "/var/run/influxdb.sock"
enabled = true
flux-enabled = true
https-certificate = "/etc/ssl/influxdb.pem"
https-enabled = false
log-enabled = true
```
Snippet of my values:
```yaml
config:
logging:
level: warn
http:
bind-address: :8086
auth-enabled: true
flux-enabled: true
log-enabled: true
write-tracing: false
pprof-enabled: true
https-enabled: false
https-certificate: …
```

fix(influxdb): pass boolean conf values as is to configmap

---

.github/workflows/helm-charts-release.yaml
.github/workflows/helm-charts-test.yaml
.github/workflows/terraform-apply.yaml
.github/workflows/terraform-plan.yaml
README.md

Superficial change, but I broke the badge name in earlier commits and decided just to "codify" the workflow names

chore: update README and use sensible workflow names

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/templates/statefulset.yaml
charts/influxdb/values.yaml

The option to provide a pre existing PVC to mount was removed during the move from Deployment to StatefulSet via https://github.com/helm/charts/pull/17619/files. Seeing that influxdb OSS runs as a single replica, mounting a pre existing PVC remains a valid option, especially helpful for data continuity across cluster rebuilds where the user recreates a PVC claiming the original (and retained) PV.

[influxdb] Add existingClaim option.

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/statefulset.yaml
charts/influxdb/values.yaml

When influxdb is serving HTTPS on API endpoint, the healthcheck probe will fail because it defaults to HTTP get instead of HTTPS, this merge request is to add an option in values.yml to setup HTTPS healthcheck if influxDB is serving HTTP requests.

add scheme to influxDB healthcheck to serve HTTPS

---

charts/kapacitor/Chart.yaml
charts/kapacitor/templates/deployment.yaml

Kubernetes removed the api version extensions/v1beta1 of deployments with version 1.16 the new api version is apps/v1
```
apiVersion "extensions/v1beta1/Deployment" was removed in Kubernetes 1.16. Use "apps/v1/Deployment" instead.
See https://git.k8s.io/kubernetes/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals for more information.
```
This PR updates the deployment specification of kapacitor to use the new api version.

update deprecated deployment api version from extensions/v1beta1 to apps/v1

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/templates/statefulset.yaml
charts/influxdb/values.yaml

Allows chart to be run as non-root user. This is required in environments where pod security policies prohibit running containers as root.

Adds optional securityContext config

---

.github/workflows/helm-charts-test.yaml
charts/telegraf-operator/.gitignore
charts/telegraf-operator/.helmignore
charts/telegraf-operator/Chart.lock
charts/telegraf-operator/Chart.yaml
charts/telegraf-operator/README.md
charts/telegraf-operator/ci/test-values.yaml
charts/telegraf-operator/templates/_helpers.tpl
charts/telegraf-operator/templates/certificate.yml
charts/telegraf-operator/templates/clusterrole.yml
charts/telegraf-operator/templates/clusterrolebinding.yml
charts/telegraf-operator/templates/deployment.yaml
charts/telegraf-operator/templates/issuer.yml
charts/telegraf-operator/templates/mutatingwebhookconfiguration.yml
charts/telegraf-operator/templates/pdb.yml
charts/telegraf-operator/templates/secret-classes.yml
charts/telegraf-operator/templates/service.yaml
charts/telegraf-operator/templates/serviceaccount.yaml
charts/telegraf-operator/values.yaml
ct.yaml

Closes https://github.com/influxdata/telegraf-operator/issues/7
This will need https://github.com/influxdata/telegraf-operator/milestone/2 to be completed
I need helm configuring this to be proper helm etiquette
What is the proper way of adding a secret with helm? @naseemkullah 
I'm thinking of adding `influxdb` as a dependency and then adding the secret to send telegraf data to influxdb instance. 
This can't be done with influxdbV2 because of all the initialization and token distribution

Add telegraf-operator chart

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/configmap.yaml

When using the key config.graphite.templates, it's being rendered twice. The first format is broken and it's preventing influxdb from starting:
>    [[graphite]]
database = "app_metrics"
enabled = true
retention_policy = "month"
separator = "_"
templates = [*.micro.service.record host.measurement.app..action.test.testField *.micro.service.record host.measurement.app2..action.test.testField2 *.micro.service.record host.measurement.app3..action.test.testField3]
templates = [
"*.micro.service.record host.measurement.app..action.test.testField",
"*.micro.service.record host.measurement.app2..action.test.testField2",
"*.micro.service.record host.measurement.app3..action.test.testField3",
]
This PR is fixing the issue.

Remove duplication of key config.graphite.templates

---

charts/chronograf/Chart.yaml
charts/chronograf/templates/ingress.yaml
charts/chronograf/values.yaml
charts/influxdb/Chart.yaml
charts/influxdb/templates/ingress.yaml
charts/influxdb/values.yaml

Modifies ingress path for chronograf and influxdb charts
Makes ingress path a template variable
Moves default path to values config
Bumps chart versions
Resolves: https://github.com/influxdata/helm-charts/issues/45

chore: allows for overridable ingress path

---

charts/chronograf/Chart.yaml
charts/chronograf/templates/ingress.yaml

The api version of `extensions/v1beta1` for the `ingress` kind is deprecated:
> warning: extensions/v1beta1/Ingress is deprecated by networking/v1beta1/Ingress and not supported by Kubernetes v1.20+ clusters.
This PR will update the api version to `networking.k8s.io/v1beta1`

fix deprecation of ingress api version

---

charts/kapacitor/Chart.yaml
charts/kapacitor/README.md
charts/kapacitor/templates/_helpers.tpl
charts/kapacitor/templates/clusterrole.yaml
charts/kapacitor/templates/clusterrolebinding.yaml
charts/kapacitor/templates/deployment.yaml
charts/kapacitor/templates/role.yaml
charts/kapacitor/templates/rolebinding.yaml
charts/kapacitor/templates/serviceaccount.yaml
charts/kapacitor/values.yaml

This PR will allow to load sideload files from config maps. The sideload files will be be placed in /var/lib/kapacitor/sideload by default but is customizable through `sidecar.sideload.folder`.
Please see the updated Readme for all new available values.
This change is based on the functionality to load dashboards in the grafana chart (https://github.com/helm/charts/tree/master/stable/grafana)
Example config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
name: kapacitor-sideload-influxdb-httpd-clienterror
labels:
kapacitor_sideload: "1"
data:
influxdb-httpd-clienterror.yml: |
[...]
```
Please let me know what you think about this. Since I'm pretty new to Kapacitor I'm open to shape this to additional needs that I'm currently not aware of.

Kapacitor sideloads

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/README.md
charts/telegraf-ds/templates/configmap.yaml

All network metrics are not necessary in `kubernetes_nodes.network*` so adding `inputs.net` is required to have node network metrics.

[telegraf-ds] add net input plugin to have node network metrics

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/templates/statefulset.yaml
charts/influxdb/values.yaml

This PR adds the functionality to mount extra volumes to the main `influxdb` container.
CC @rawkode
- Follows the conventions laid out in #88 
- Closes #89

feat: add extra volume mounting functionality to influxdb chart

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/values.yaml

Previously, support was added for this with the `volumeMounts` key. I've opted not to modify this and instead provide a more flexible solution through `volumes` and `mountPoints` keys.
We'll aim to deprecate the older method in a future release.

feat: add ability to provide volumes and mountPoints

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/statefulset.yaml

Overriding the `resources` section using a simple `values.yaml` fails due to wrong indentation of the resulting yaml.
Specifying this `values.yaml`:
```
resources:
limits:
cpu: 100m
memory: 128Mi
requests:
cpu: 100m
memory: 128Mi
```
with
```
helm template -f values.yaml influxdata/influxdb2 --debug
```
results in
```
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: influxdb2
app.kubernetes.io/instance: RELEASE-NAME
serviceName: "RELEASE-NAME-influxdb2"
template:
metadata:
labels:
app.kubernetes.io/name: influxdb2
app.kubernetes.io/instance: RELEASE-NAME
spec:
volumes:
- name: data
persistentVolumeClaim:
claimName: RELEASE-NAME-influxdb2
containers:
- name: influxdb2
image: "quay.io/influxdb/influxdb:2.0.0-beta"
imagePullPolicy: IfNotPresent
ports:
- name: http …
```

Fix resources indentation

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml

To get stats for all network interfaces, it's nice to be able to run with hostNetwork: true. And if you do that, you also want to set dnsPolicy to ClusterFirstWithHostNet.
This adds the `hostNetwork` and `dnsPolicy` options to telegraf-ds values

feat: Add support for hostNetwork: true to telegraf-ds

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/_helpers.tpl

Nested TOML tables should only be surrounded by a single bracket.
Fixes #97.
Co-authored-by: Zac Bergquist <bergquistz@vmware.com>

Fix rendering of input configuration.

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/templates/backup-cronjob.yaml
charts/influxdb/templates/backup-pvc.yaml
charts/influxdb/values.yaml

cc @monotek
Heavily inspired by @monoteks suggestions, this allows users to use a PVC either as their long term or intermediary storage for backups. Disabled by default.
Anyway we could get your approval @monotek?

feat: add option to use PVC for backups -- thanks monotek

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/_helpers.tpl
charts/telegraf-ds/templates/configmap.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/templates/role.yaml
charts/telegraf-ds/templates/rolebinding.yaml
charts/telegraf-ds/templates/serviceaccount.yaml
charts/telegraf/Chart.yaml
charts/telegraf/templates/_helpers.tpl
charts/telegraf/templates/configmap.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/templates/role.yaml
charts/telegraf/templates/rolebinding.yaml
charts/telegraf/templates/service.yaml
charts/telegraf/templates/serviceaccount.yaml

I've noticed the labels for telegraf & telegraf-ds were a bit messed up.
Refactored them into template variables and made sure they are consistent throughout the charts.

clean up labels for telegraf/telegraf-ds

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml
charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/values.yaml

Added support to telegraf/telegraf-ds chart to be able to pass command line args to Telegraf containers, e.g. for customers needing support to load configs from telegraf.d config-directory volumes.

allow passing args in telegraf/telegraf-ds

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/_helpers.tpl

I've tried to use `tagdrop` on the MongoDB Input Plugin:
```yaml
- mongodb:
...
tagdrop:
db_name:
- "a"
- "b"
- "c"
```
This leads to incorrect TOML (On the first element is the `,` missing):
```toml
[inputs.mongodb.tagdrop]
db_name = [
"a"
"b",
"c",
]
```
The provided change fixes this.
---

[telegraf] used wrong variable on parsing the telegraf configuration

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/service.yaml
charts/influxdb/templates/statefulset.yaml

This commit sets `collectd` service as UDP instead of TCP.
fixes #107

set collectd service as a UDP service

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/templates/backup-cronjob.yaml
charts/influxdb/values.yaml

Add support for backup of InfluxDB to Amazon S3 (or compatible). To use it please create the following secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: aws-credentials-secret
namespace: your-influxdb-namespace
type: Opaque
stringData:
credentials: |
[default]
aws_access_key_id=XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```
and edit the `backup.s3` section in _values.yaml_.

InfluxDB backup to Amazon S3 (or compatible)

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/templates/service.yaml

Some loadbalancer (i.e. MetalLB) support spec.loadbalancerIP to specify an IP address for a service. I'd like the influx helm chart to support this in Values.
Tested on my own cluster against MetalLB:
my values.yml:
```
...
service:
type: LoadBalancer
loadBalancerIP: 192.168.1.56
```
```
k get services -n monitoring
NAME       TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)                         AGE
influxdb   LoadBalancer   10.152.183.118   192.168.1.56   8086:31518/TCP,8088:31932/TCP   7m19s
```
Default deploy with default values post-change also successful.
Signed-off-by: Dennis Zhang <dennis.zhang.nrg@gmail.com>

[InfluxDB Helm] Add support for loadbalancerIP

---

charts/influxdb-enterprise/templates/data-statefulset.yaml
charts/influxdb-enterprise/templates/meta-statefulset.yaml

As per documented configuration in [values.yaml](https://github.com/influxdata/helm-charts/blob/master/charts/influxdb-enterprise/values.yaml#L17), when `license` is using `secret` configuration, `key` can be set to anything.
Without this patch, `/var/run/secrets/influxdb/license.json` will be mounted as a directory!! Making the bug very difficult to discover.
This patch enables the configuration work as per documentation.

Mount license from secret using configurable key, instead of hardcoded key

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/service.yaml

This PR fixes service.yaml for `tcp_listener` and `udp_listener`.
When you set `udp_listener` or `tcp_listener` in `values.yaml`, the comparison fails and the service isn't correctly setup. Fixing the comparison shows that the Kubernetes port name is also incorrect, it needs dashes instead of underscores. This PR fixes both issues for each listener.

Fix underscores and dashes in service.yaml

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/templates/data-statefulset.yaml
charts/influxdb-enterprise/templates/meta-statefulset.yaml

This PR fixes key references in [data|meta].statefulset.yaml for the chart for 
- secret.key
- secret.crt

fix: key references in statefulset.yaml files

---

charts/chronograf/Chart.yaml
charts/chronograf/templates/deployment.yaml

* Support Chronograf `--basepath`, `$BASE_PATH` options in chart.
- [x ] CHANGELOG.md updated (Uses documented Chronograf environment variable, env: {} is documented.)
https://docs.influxdata.com/chronograf/v1.8/administration/config-options/#basepath-p
- [x ] Rebased/mergable
- [ x] Tests pass (See Below)
- [ x] Sign [CLA](https://influxdata.com/community/cla/) (if not already signed)
`helm template chronograf --set env.BASE_PATH="/chronograf"`
```
env:
- name: "BASE_PATH"
value: "/chronograf"
- name: "HOST_PAGE_DISABLED"
value: "true"
ports:
- containerPort: 8888
name: api
livenessProbe:
httpGet:
path: /chronograf/ping
port: api
readinessProbe:
httpGet:
path: /chronograf/ping
port: api
```
`helm template chronograf`
```
env:
- name: "HOST_PAGE_DISABLED"
value: "true"
ports:
- …
```

Prepend basepath to liveness and readiness probes.

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/templates/bootstrap-job.yaml
charts/influxdb-enterprise/templates/data-configmap.yaml

This PR fixes the data-configmap under the [http] section of the TOML 
Currently using the same x509s as the [cluster] settings, but will still want to update chart to support different DNS names for RPC and HTTP.

fix(enterprise): HTTPs config for data port

---

charts/influxdb2/Chart.yaml
charts/influxdb2/README.md
charts/influxdb2/templates/secret.yaml
charts/influxdb2/values.yaml

This PR makes `adminUser.password` and `adminUser.token` optional values that can be set on user's `value.yaml` file. 
Current users of this chart won't  need to change anything if they want to keep using random values as usual. 
One usecase for this feature is to use the chart inside an operator created with the [operator-framework/operator-sdk](https://github.com/operator-framework/operator-sdk). In this case the reconciliation algorithm used by the SDK will handle the secrets and recreate it during its lifecycle. So, setting a fixed token and password gives more control over the admin credentials.
Closes #145

feat(influxdb2): add optional values for password and token

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/values.yaml
charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/values.yaml

This adds the podLabels property to values.yaml to let users specify custom labels on generated pods, e.g. to follow company requirements.
CLA signed.

influxdb/telegraf: add configurable pod labels

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb/Chart.yaml
charts/telegraf/Chart.yaml

There was an InfluxDB Enterprise PR merged 6 days ago that caused a few charts to publish, as its version wasn't incremented.
This should hopefully get everything up to date.

Version Bumps

---

charts/telegraf-operator/Chart.yaml

This PR fixes https://github.com/influxdata/helm-charts/issues/150

Changing telegraf-operator kubeVersion to support EKS

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml

Allow the setting of priorityClassName on the daemonset. 
Fixes #78 
Ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/

Add option to set priorityClassName

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-operator/Chart.yaml

This PR should fix the recently failed releases:
- #168 was successfully released as https://github.com/influxdata/helm-charts/releases/tag/telegraf-operator-1.1.1
- #154 should be released as `telegraf-operator-1.1.2` after merge
- #178 should be released as `telegraf-ds-1.0.16` after merge
Although #178 was successfully tagged and released as `telegraf-ds-1.0.15` it was never added to the chart index.
Based on https://github.com/helm/chart-releaser-action/blob/master/cr.sh#L56 the GitHub action will not detect `1.0.15` to be added to the index as far as I can tell. I have no easy way to test it without self hosting a chart repo myself, any guidance is welcome if you maintainers have more experience with the chart-releaser-action.

(Fix #182) Fix releases

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/statefulset.yaml
charts/influxdb/values.yaml

This PR adds to the InfluxDB chart a [similar mechanism we have in the Chronograf chart](https://github.com/influxdata/helm-charts/blob/master/charts/chronograf/values.yaml#L122-L124) to add values to the environment from a secret. 
I need this to set the `INFLUXDB_HTTP_SHARED_SECRET` to configure [auth using JWT tokens.](https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#authenticate-using-jwt-tokens)
I've tested the manifest generated from this change using `helm template . <my values yaml>` and `kubectl -f apply <manifest yaml>` and verified that the `shared-secret` configuration is present in the `[http]` session of the InfluxDB config.

feat(influxdb): Add values to the environment from a secret

---

charts/telegraf-operator/Chart.yaml
charts/telegraf-operator/templates/_helpers.tpl
charts/telegraf-operator/templates/deployment.yaml

After helm upgrade for non cert manager installation, the CA in webhook is updated, but secret left unchanged what leads to tls errors (certificates aren't signed by the new CA).
This PR additionally add annotations (as recommended in [official documentation](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments)) to reload deployment in case of secret change. It's required to reload certificates from secret as k8s uses new CA to validate requests

[telegraf-operator] Fix certificate issue related to helm upgrade

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/statefulset.yaml

Otherwise the first line will be indented up to the existing indent on the line:
```
tolerations:
- key: mykeyhere
operator: EXISTS
```
> Error: YAML parse error on influxdb2/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 51: did not find expected key
helm.go:94: [debug] error converting YAML to JSON: yaml: line 51: did not find expected key
vs.
```
tolerations:
- key: mykey
operator: EXISTS
```

Use nindent for statefulset tolerations etc.

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/service.yaml

Tested locally on a kube cluster. Let me know if there's anything else I need to address in PR 
- [n/a] Tests pass

Adding support for influxdb_listener since http_listener is deprecated

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/serviceaccount.yaml
charts/telegraf/values.yaml

I did not find a CHANGELOG to update.
Added this to allow users to make use of GKE IAM Workload or EKS IAM Role for Service Accounts.
```
$ helm template charts/telegraf -s templates/serviceaccount.yaml  --set "serviceAccount.annotations.foo=bar" --set "serviceAccount.annotations.bar=baz"
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: RELEASE-NAME-telegraf
labels:
helm.sh/chart: telegraf-1.7.23
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: telegraf
app.kubernetes.io/instance: RELEASE-NAME
annotations:
bar: baz
foo: bar
```

[telegraf] Support Annotations for ServiceAccount

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/service.yaml
charts/influxdb2/templates/statefulset.yaml

- bumped up influxdb version to 2.0.0-rc
- change default port (9999 -> 8086) ([description](https://github.com/influxdata/influxdb/releases/tag/v2.0.0-rc.0))

influxdb2: bumped up to 2.0.0-rc

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/meta-statefulset.yaml
charts/influxdb/templates/statefulset.yaml
charts/influxdb/values.yaml

GKE ingress needs healthchecks path `/ping?verbose=true` as [10321](https://github.com/influxdata/influxdb/pull/10321) is now implemented. 
Fixes # [15165](https://github.com/helm/charts/issues/15165)

Allow to customize healthchcks for liveness, readiness, startup probes

---

.github/workflows/helm-charts-release.yaml

I'm hoping that this means we only trigger a release
when the push is to the master branch and a Chart.yaml was
modified.
We've found that automatically releasing on push to master alone
causes a lot of problems, especially as we forget to encourage contributors
to bump the version; even reminding them isn't a great experience.
This should allow us to have a successful build without such a change
and then manually update the Chart version ourselves, without build
failures

chore: improve release process to be more forgiving

---

charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/influxdb/templates/statefulset.yaml
charts/influxdb/values.yaml

Currently, there is no option to add custom sidecar containers in the InfluxDB pod. A common use case for this extension can be monitoring, for example running a custom Prometheus exporter monitoring arbitrary resource consumption (in our case the database disk usage).
This PR enables adding custom sidecar workloads in the InfluxDB pod by defining `extraContainers` in `values.yaml` file.

Add extraContainers option for running custom sidecar workloads in the InfluxDB pod

---

charts/influxdb/Chart.yaml
charts/influxdb/files/backup-retention-script.sh
charts/influxdb/templates/backup-retention-configmap.yaml
charts/influxdb/templates/backup-retention-cronjob.yaml
charts/influxdb/values.yaml

This PR enables automatic time-based retention of InfluxDB backups with implementation for S3 and placeholders for other storage providers.

feat(influxdb): add backup retention

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/_helpers.tpl
charts/telegraf/templates/configmap.yaml

This is similar to https://github.com/influxdata/helm-charts/pull/100 which fixed the `input` side of plugins, same change for the `output` side.

Nested TOML tables should only be surrounded by a single bracket.

---

charts/telegraf-operator/Chart.yaml
charts/telegraf-operator/templates/deployment.yaml
charts/telegraf-operator/values.yaml

Adds support for `--require-annotations-for-secret` introduced in influxdata/telegraf-operator#42 that allows enforcing checking of annotation for secret used for storing telegraf configuration.
Not enabled by default as this flag should not be enabled on any existing deployment of `telegraf-operator` since secrets created prior to influxdata/telegraf-operator#42 will not have the annotation set.

feat(telegraf-operator): add optional --require-annotations-for-secret flag

---

charts/influxdb-enterprise/example-resources.yaml
charts/influxdb-enterprise/values.yaml

- Unified defaults for configuration objects so they can be clearly identified when namespace contains more deployments.
- Fixed naming mismatch for sample TLS secret and default in values.yaml

prefix secrets and configmaps with influxdb

---

charts/influxdb-enterprise/templates/bootstrap-job.yaml

Resource limits on init job might fail deployment of InfluxDB cluster. Main offender is hardcoded 10MB RAM limit on final container which is too tight and in some circumstances results in endless loop of attempts to start the container. Since this is single point of failure and job runs only once I would like to propose removal of these limits completely. Second option would be to use the `{{- toYaml .Values.bootstrap.ddldml.resources | nindent 10 }}` for final container as well.
(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = container create failed: time="2020-10-21T16:25:24Z" level=warning msg="signal: killed" time="2020-10-21T16:25:24Z" level=error msg="container_linux.go:349: starting container process caused \"process_linux.go:365: …

fix: bump resource limits for init job

---

charts/influxdb-enterprise/values.yaml

Enterprise deployments should run in HA setup. This PR adds sensible default configuration that try to deploy data and meta containers on different workers in K8s cluster if possible by default.

use pod anti-affinity to support HA deployment by default

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/templates/_helpers.tpl
charts/influxdb-enterprise/templates/bootstrap-job.yaml
charts/influxdb-enterprise/templates/data-statefulset.yaml
charts/influxdb-enterprise/templates/meta-statefulset.yaml
charts/influxdb-enterprise/templates/serviceaccount.yaml
charts/influxdb-enterprise/values.yaml

PR adds configuration for service account used by InfluxDB deployment. This feature is required in some environments where service account extends basic security model such as AWS EKS or OpenShift Enterprise platform. Feature allows user to create new account directly from deployment or use already pre-created one.

add service account configuration for influxdb deployment

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/configmap.yaml
charts/telegraf-ds/values.yaml

This is intended as a partial fix/workaround for #221; a more complete fix will require waiting for a fix to bugs in Helm itself, which could take some time. This PR provides an "escape hatch" as where the end user can hand-write their own TOML if necessary. This was discussed as an option by @rawkode [in a comment](https://github.com/influxdata/helm-charts/issues/221#issuecomment-710766207) on the issue.
To use the escape hatch, set `config_override.toml` to a string containing the full contents of a valid Telegraf config file.
The more complete fix is at core waiting on kubernetes-sigs/yaml#45 to be fixed, and then for that fix to make its way into a new release of Helm.

[telegraf-ds] Add option for simple override of TOML config file contents

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/backup-cronjob.yaml

Fixes influxdata/helm-charts#240
When a PVC is used before the data upload then it fills up quickly after some backups because always a new timestamped folder is created.
This PR fixes the problem by removing all folders located under `/backup/*`after uploading them.

[influxdb] Remove folders from PVC after uploading

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/job-setup-admin.yaml
charts/influxdb2/templates/persistent-volume-claim.yaml
charts/influxdb2/templates/statefulset.yaml
charts/influxdb2/values.yaml
charts/telegraf/Chart.yaml
charts/telegraf/templates/configmap.yaml
charts/telegraf/templates/service.yaml
charts/telegraf/values.yaml

Added metrics key to enable/disable internal metrics and minor bug fixes for influxdb2

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/job-setup-admin.yaml
charts/influxdb2/values.yaml

Setting 'create' to 'true' as it's generally wanted, but now the flag
exists so it can be skipped. I tested this locally with both options to
make sure it worked, and I copied the naming from influx1's chart, but
feel free to make changes as necessary.

allow admin user creation to be skipped

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/ingress.yaml
charts/influxdb2/templates/service.yaml
charts/influxdb2/templates/statefulset.yaml
charts/influxdb2/values.yaml

This makes it possible to define different service type and set AWS ALB using annotations

Add service type and ingressClass to influxdb2

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/configmap.yaml

In the current implementation, a misplaced `{{- end }}` in the chart causes the `{{ template "inputs" .Values.config.inputs -}}` call to be inside the `{{- if .Values.metrics.health.enabled }}` conditional block.
This fixes that.

[telegraf] Fix: Cannot define inputs without health check

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/job-setup-admin.yaml
charts/influxdb2/templates/statefulset.yaml
charts/influxdb2/values.yaml

This makes it possible to specify annotations for the pods created by the `influxdb2` chart.
This is handy for things like configuring Istio sidecar injection.

Make InfluxDB 2 pod annotations configurable

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/job-setup-admin.yaml
charts/influxdb2/values.yaml

Hi,
I propose adding -r flag, which sets retention policy of bucket, to the influx setup script in jobs_setup_admin.yaml. It helps me to remove the manual part of process, when I need to set up the same retention policy on different environments, which differs from the default one.
The default value of retention policy can live in the values.yaml and be overridden if necessary.
This was tested with helm install on my testing cluster with default value 0s and with overriding value 1440h.

[influxdb2] add r flag to job_setup_admin tpl, add rp to values

---

charts/influxdb/Chart.yaml
charts/influxdb/values.yaml

Helm does not seem to evaluate `nil` as false, but it does with `null`. This fixes #277, introduced by #272 / 108378f.

Fix default value for ingress class name

---

charts/influxdb2/Chart.yaml
charts/influxdb2/README.md
charts/influxdb2/templates/NOTES.txt
charts/influxdb2/templates/job-setup-admin.yaml
charts/influxdb2/templates/secret.yaml
charts/influxdb2/values.yaml

I've missed the possibility to use existing secret for the admin password and the token.
For the implementation I followed the Helm Chart for InfluxDB 1.

[influxdb2] Add possibility to use existing secret for admin password

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/templates/role.yaml
charts/telegraf/templates/rolebinding.yaml
charts/telegraf/values.yaml

Add ability to pass sensitive environment variables to telegraf environment.
Specific use case might be passing `$INFLUX_TOKEN` or any other API token:
Example `values.yaml` will look like this:
```
...
envFromSecret: "telegraf-tokens"
env:
- name: HOSTNAME
value: "telegraf-polling-service"
- name: INFLUX_ORG
value: influxdata
- name: INFLUX_HOST
value: https://example.com
...
config:
agent:
...
hostname: "$HOSTNAME"
omit_hostname: false
outputs:
- influxdb_v2:
urls:
- "${INFLUX_HOST}"
token: "${INFLUX_TOKEN}"
organization = "${INFLUX_ORG}"
...
```

[telegraf] Add envFromSecret to pass sensitive data into environment

---

charts/telegraf/templates/service.yaml

Hello there! 👋
While using the chart I've noticed that the UDP listener plugin has been deprecated in favor of the [socket_listener plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/socket_listener).
However configuring `socket_listener` didn't expose the port in the K8s service as I expected.
I've based the changes in the supported protocols in the [socket_listener plugin readme file](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/socket_listener).
So basically I check if the value starts with "udp" or "tcp", if they do I add the port to the K8s service.
To support multiple entries I added the port number to the port name. 
Please check the output section to see how the service looks like after this change.
Logs with deprecation:
``` …
```

Add input socket_listener port to K8s Service when it is UDP or TCP

---

index.md

Update the helm repo url to the correct location. Helm is looking for `index.yaml` which is served at https://helm.influxdata.com/index.yaml. Using the incorrect url as is currently in the instructions, the helm chart index would be served from https://helm.influxdata.com/helm-charts/index.yaml

fix(gh-pages): update page with correct repo url

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/templates/role.yaml
charts/telegraf-ds/templates/rolebinding.yaml
charts/telegraf-ds/values.yaml

Currently the Helm chart mounts `/proc` on `/rootfs/proc` but even after setting `HOST_PROC=/rootfs/proc` a `cat` on `/proc/self/mounts` or a `df` inside the container shows information for the container and not for the host.
Mounting the host filesystem following [this FAQ](https://github.com/influxdata/telegraf/blob/master/docs/FAQ.md#q-how-can-i-monitor-the-docker-engine-host-from-within-a-container) fixes it.

Fix telegraf-ds mounts

---

charts/influxdb2/Chart.yaml
charts/influxdb2/values.yaml

- updates version to 2.1.1
- fixes mountPath to match influxdb2 image filesystem and description (the image contains and [description](https://registry.hub.docker.com/_/influxdb/) describes path `/var/lib/influxdb2`). Together with https://github.com/influxdata/influxdata-docker/pull/549 should end confusion in #350.

fix(influxdb2): update version and fix path

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/ingress.yaml

InfluxDB's Helm chart was lacking v1 ingress support, which makes it impossible to deploy on Kubernetes 1.22. This PR makes helm auto-detect if v1 ingress is possible.

influxdb: support v1 ingress

---

charts/influxdb/Chart.yaml
charts/influxdb/templates/ingress.yaml

Ensure that the Ingress object is present in networking.k8s.io/v1, before rendering that version of the object.
Some versions of k8s (ie. 1.16), have the v1 api, but it does not include the Ingress, which causes the install to fail, when the ingress is enabled.
The helm documentation states that it is possible to check for an objects presence in an api group:
https://helm.sh/docs/chart_template_guide/builtin_objects/

Fix ingress capability check in influxdb

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/ingress.yaml

Not sure if this was by design, but to get the code working I had to copy the config from `influxdbv1` to `influxdbv2` which had the v1 networking config. `influxdbv2` has `v1beta1` at least on the master branch that is. I just copied it over as is and it has worked since I did that. I am sure other folks will run into the problem if not already.
Version 1 has the new config and version 2 has the old one.

Update ingress to v1 from v1beta1 for Influxdb2.

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/ingress.yaml

In #386 the service port was hard coded to port 8086. Unfortunately, that's not necessarily the port that the service exposes. In fact, it's not even the default!
The default values.yaml config uses port 80 for the service. Since the ingress specifies the service port, not the container port, the ingress specification doesn't work as expected.

Use port name for backend selector in influxdb2

---

charts/influxdb2/Chart.yaml
charts/influxdb2/README.md

Fixes #393 
- removes warning about beta version
- fixes data path info in persistence info and reference to image (quay -> docker hub)

docs: fix influxdb2 chart README

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml

This allow setting `dnsConfig` when `dnsPolicy` is set to None
Signed-off-by: Seena Fallah <seenafallah@gmail.com>

telegraf-ds: add support setting dnsConfig

---

charts/influxdb2/Chart.yaml
charts/influxdb2/templates/statefulset.yaml
charts/influxdb2/values.yaml

This PR makes all kubernetes probes in the influxdb2 chart configurable in a way similar to what the influx v1 chart allows.
PR Checklist:

Make liveness/readiness/startup probes for influxdb2 chart configurable

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/_helpers.tpl

Fixes #382 
- Renders `percentiles` (plugins `statsd`, `ping`) as floats (with trailing `.0` for input values without decimals, it's harmless).
- Also updates Telegraf version to 1.20.4
values:
```
config:
inputs:
- statsd:
service_address: ":8125"
percentiles:
- 50
- 95
- 99
- 99.5
metric_separator: "_"
allowed_pending_messages: 10000
percentile_limit: 1000
```
output:
```
[[inputs.statsd]]
allowed_pending_messages = 10000
metric_separator = "_"
percentile_limit = 1000
percentiles = [
50.0,
95.0,
99.0,
99.5
]
service_address = ":8125"
```

[telegraf] render percentiles as floats

---

charts/kapacitor/Chart.yaml
charts/kapacitor/README.md
charts/kapacitor/templates/deployment.yaml
charts/kapacitor/values.yaml

Add possibility to specify `kapacitor` deployment strategy type.
It isn't possible to alter the kapacitor deployment strategy. In our case we don't have a RWX PVC and that causes trouble on rollouts of new versions.
---

[Kapacitor] Add way to set kapacitor strategy type

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/configmap.yaml

Fix issue when a pod with telegraf-ds can't start due to absence of bearer token.
Resolves issue #310

Fix ServiceAccount token mounth path

---

charts/telegraf/Chart.yaml
charts/telegraf/ci/default-values.yaml
charts/telegraf/ci/metrics-health-enabled-values.yaml
charts/telegraf/templates/_helpers.tpl
charts/telegraf/templates/configmap.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/templates/service.yaml
charts/telegraf/values.yaml

- closes #406 
- adds test files for default values test and metrics health enabled
- closes #264 
-  `internal` plugin is enabled by default for backward compatibility, can be disabled with `metrics.internal.enabled: false`
- updates Telegraf to 1.21.2

Fix probes and internal metrics configuration

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/service.yaml

automatically expose syslog port as defined in config.inputs
this fixes issue #164 
```
```

expose syslog port

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml

This PR exposes the Telegraf pod's SecurityContext as a user-configured value, allowing the user to provide the `runAsUser`/`runAsGroup` parameters in the Telegraf-DS chart. (The SecurityContext is already exposed in similar way in the Telegraf and Telegraf-Operator charts.) Since Telegraf 1.20.3, providing a non-default `runAsGroup` value is crucial to being able to use the Docker input plugin (see [Docker: Run Telegraf as non-root](https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/)).
I tested the fix by running `helm template` and examining the output.

Telegraf-DS: parametrize the pod's SecurityContext

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/serviceaccount.yaml
charts/telegraf-ds/values.yaml

Adds support for annotations in the ServiceAccount.
Facilitates easier installation of the chart into EKS clusters, when using IRSA (IAM roles for service accounts).
With annotations:
```
$ helm template charts/telegraf-ds -s templates/serviceaccount.yaml  \
--set "serviceAccount.annotations.foo=bar" \
--set "serviceAccount.annotations.bar=baz"
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: RELEASE-NAME-telegraf-ds
labels:
helm.sh/chart: telegraf-ds-1.0.29
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: telegraf-ds
app.kubernetes.io/instance: RELEASE-NAME
annotations:
bar: baz
foo: bar
```
Without annotations:
```
$ helm template charts/telegraf-ds -s templates/serviceaccount.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: RELEASE-NAME-telegraf-ds
labels: …
```

[telegraf-ds] support annotations on serviceaccount

---

.github/workflows/helm-charts-test.yaml
charts/chronograf/Chart.yaml
charts/chronograf/templates/ingress.yaml
charts/influxdb/Chart.yaml
charts/influxdb/templates/backup-cronjob.yaml
charts/influxdb/templates/backup-retention-cronjob.yaml
charts/influxdb2/Chart.yaml
charts/influxdb2/templates/pdb.yaml
charts/kapacitor/Chart.yaml
charts/kapacitor/templates/role.yaml
charts/kapacitor/templates/rolebinding.yaml
charts/telegraf/Chart.yaml
charts/telegraf/templates/pdb.yaml

charts:
- adds support for `v1` APIs (networking, auth, policy, batch) to: `chronograf`, `influxdb`, `influxdb2`, `telegraf`, `kapacitor`
closes #286 
closes #329
workflow:
- extends checks to run also with `v1.22` k8s, where several `v1beta1` APIs have been removed, and
- updates cert manager from `0.15.1` (k8s support only up to `1.21`) to `1.5.4` (k8s 1.16-1.22)
Until now, test ran on v1.21.1 (default for `helm/kind-action@v1.2.0` / `kubernetes-sigs/kind@0.11.1` respectively). This is kept, the version explicitly listed. **Check `lint-test` is obsolete.**

Support Kubernetes 1.22+

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/templates/data-service.yaml
charts/influxdb-enterprise/templates/meta-service.yaml
charts/influxdb-enterprise/values.yaml

It should be possible to ingest data to influxdb via cloud internal load balancer.
> To set an internal load balancer, add one of the following annotations to the Service depending on the cloud Service provider you're using. 
(ref. [https://kubernetes.io/docs](https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer))
**Example: Azure**
```
annotations: 
service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```
**Applied tests:**
```
helm lint ./influxdb-enterprise
```
resulted to:
```
==> Linting ./influxdb-enterprise
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
```
```
helm template --set data.service.annotations.service\\.beta\\.kubernetes\\.io/azure-load-balancer-internal=true influxdb-enterprise …
```

[influxdb-enterprise] add annotations to data.service

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/README.md
charts/telegraf-ds/templates/daemonset.yaml

`daemonset` template:
- removed non-printable unicode character
Closes #289 
- fixed `hostNetwork` default
`README.dm`:
- fixed example of usage intruction
Closes #316

[telegraf-ds] minor fixes

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/configmap.yaml

Hello,
Since https://github.com/influxdata/helm-charts/pull/441 in my usage I have the current values:
```yaml
---
config:
global_tags:
foo: bar
```
And when `helm template testing .`, I've got:
```yaml
Error: YAML parse error on telegraf/templates/configmap.yaml: error converting YAML to JSON: yaml: line 11: did not find expected comment or line break
```

fix(telegraf): configmap rendering error

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/templates/data-statefulset.yaml
charts/influxdb-enterprise/templates/meta-statefulset.yaml
charts/influxdb-enterprise/values.yaml

I had to open a new PR due to a mess up. The old PR is: https://github.com/influxdata/helm-charts/pull/439
It shoule be possible to configure environment variables in enterprise chart as well. 
There is another PR related to this change (https://github.com/influxdata/helm-charts/pull/290) but didn't seem to be getting the update it was needed. 
**changed files**
* update meta-statefulset.ymal
* update data-statefulset.yaml
* update values.yaml
* update Chart.yaml (chart version to v0.1.18)
**Applied test 1**
`helm lint ./influxdb-enterprise`
**Result**
```
==> Linting ./influxdb-enterprise
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
```
**Applied test 2**
`helm template --set data.env.INFLUXDB_ANTI_ENTROPY_ENABLED=true influxdb-enterprise …

[influxdb-enterprise] Enable configuration of environment variables

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/ci/default-values.yaml
charts/telegraf-ds/ci/docker-no-endpoint-values.yaml
charts/telegraf-ds/templates/configmap.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml

- `inputs.docker` endpoint can be specified with `config.docker_endpoint` value, default is `unix:///var/run/docker.sock`, empty string disables the plugin
Closes #267
Closes #320

[telegraf-ds] configurable docker plugin socket

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/templates/data-service.yaml
charts/influxdb-enterprise/templates/meta-service.yaml
charts/influxdb-enterprise/values.yaml

This PR allows customizing influxdb-enterprise meta service the same way as it is already possible for the data service. I.e.
`meta.service.type` can change the k8s service type and a few other other attributes can be specified when using `LoadBalancer` service type. 
Additionally `meta.service.nodePort` and `data.service.nodePort` can further specify fixed (main) HTTP node ports when `NodePort` service type is used.
These changes make it easy for me to customize `influxdb-enterprise` helm chart locally for development, by changing data/meta services to `NodePort` and assigning a specific `nodePort`.
```
helm upgrade --install influxdb influxdata/influxdb-enterprise --namespace default \
--set-string envFromSecret=influxdb-license \
--set-string data.service.type=NodePort \
--set-string …
```

feat(influxdb-enterprise): allow to customize meta service properties

---

charts/influxdb/Chart.yaml
charts/influxdb/files/backup-retention-script.sh
charts/influxdb/templates/backup-cronjob.yaml
charts/influxdb/values.yaml

- adds `nodeSelector` support for backup ->
- Closes #199 
- Closes #298 
- fixes handling of optional S3 backup `endpointUrl` option ->
- Closes #328

[influxdb] fix backup job

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml

This PR adds labels, annotations and env from secret support. It's copied from `telegraf` chart.
- enables expose secret key as env  -> Closes #63 
- annotations are used to specify apparmor profile -> Closes #284

[telegraf-ds] add pod labels, annotations and env from secret support

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml

Hello! :wave: 
I am submitting this PR because I have been trying to deploy telegraf into a namespace with the [restricted pod security standard profile](https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-admission-labels-for-namespaces). As an example, the namespace looks something like this (note: this only works by default on clusters 1.23+):
```yaml
apiVersion: v1
kind: Namespace
metadata:
annotations:
labels:
pod-security.kubernetes.io/enforce: restricted
pod-security.kubernetes.io/warn: restricted
name: test
```
There is a key in the `deployment.yaml` file already (on line 28) for `securityContext`, but this is at the **pod** level, and *not* the **container** level. To meet the requirements of the [restricted …

Add containerSecurityContext in telegraf deployment template

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/_helpers.tpl

Updates to the telegraf version are blocked due to failing CI. This resolves the CI issues.
replaces: #499
fixes: #498

fix: sync telegraf-ds to properly format output subtables

---

charts/telegraf-operator/Chart.yaml
charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml

When default sidecar resources don't fit someone's need it's
preferable to specify a custom default value instead of adding annotations
to every pod that runs sidecar.
So this PR exposes variables to configure default sidecar resources.
This was tested by specifying custom values for default resources and deploying to k8s.
`kubectl describe pod` showed that telegraf sidecar has resources specified using `values.yaml`

Make sidecar default resources configurable

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/README.md
charts/influxdb/Chart.yaml
charts/influxdb/README.md
charts/telegraf/values.yaml

Per issue #519 this PR removes configuration options that are specific to InfluxDB _Enterprise_ and moves them to the Enterprise chart.

Enterprise Helm Chart README Refactor

---

charts/telegraf/Chart.yaml
charts/telegraf/values.yaml

This helps avoid a bad actor changing your default registries to force fetching unexpected images.
My auditors prefer explicit container paths so that there is no mystery where the objects are fetch from.

fix: use explicit path to container registry

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/values.yaml

This makes it possible to configure the updateStrategy for the Telegraf Deployment. 
In our use case and clusters we have `podAntiAffinity` configured for the Telegraf Deployment and to avoid pods being stuck in state `Pending` we also want to set `updateStrategy.type: Recreate`.
I've manually tried this change with:
```
updateStrategy: {}
```
```
updateStrategy:
type: RollingUpdate
rollingUpdate:
maxUnavailable: 1
maxSurge: 1
```
```
updateStrategy:
type: Recreate
```
Which all correctly set the `strategy` on the Deployment.

Add updateStrategy to Telegraf Deployment.

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml

When telegraf-ds helm chart is deployed the HOSTIP env arg is duplicated in the daemonset.

Removed duplicated HOSTIP

---

charts/telegraf-operator/Chart.yaml

New [`telegraf-operator`](https://github.com/influxdata/telegraf-operator/releases/tag/v1.3.11) release, follow up here.

release: update for `telegraf-operator@v1.3.11`

---

charts/telegraf-ds/templates/role.yaml

The telegraf-ds chart with `inputs.kube_inventory` logs the following errors:
```
E! [inputs.kube_inventory] Error in plugin: persistentvolumes is forbidden: User "system:serviceaccount:telegraf:telegraf-telegraf-ds" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E! [inputs.kube_inventory] Error in plugin: nodes is forbidden: User "system:serviceaccount:telegraf:telegraf-telegraf-ds" cannot list resource "nodes" in API group "" at the cluster scope
```
This PR adds the missing permissions to the `influx-stats-viewer` ClusterRole.

Add missing permissions for telegraf ClusterRole

---

charts/telegraf-ds/Chart.yaml
charts/telegraf-ds/templates/daemonset.yaml
charts/telegraf-ds/values.yaml

Add support for `imagePullSecrets` in `telegraf-ds`. With the DockerHub pull rate limiting it's important that users are able to provide auth creds for DockerHub.
There is a previous MR: https://github.com/influxdata/helm-charts/pull/558, but it is quite old and out of date.

[telegraf-ds] add imagePullSecrets support

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/service.yaml

Currently, if using the `opentelemetry` input plugin for telegraf, the kubernetes service is not created because this input plugin is not taken into account when setting the ports for the service.
This PR is about adding this support.
Example of values file:
```
resources: {}
service:
enabled: true
config:
agent:
interval: "10s"
round_interval: true
metric_batch_size: 1000
metric_buffer_limit: 10000
collection_jitter: "0s"
flush_interval: "10s"
flush_jitter: "0s"
precision: ""
debug: true
quiet: false
inputs:
- opentelemetry:
service_address: ":4311" #address to receive traces
timeout: "5s"
metrics_schema: "prometheus-v2"
processors:
- starlark:
source:
|
load("logging.star", "log")
def apply(metric):
log.info("Processing metric: {}".format(metric))
return metric
outputs:
- file:
files : …
```

Telegraf helm chart: Adding support for opentelemetry input in service template

---

charts/influxdb3-clustered/Chart.yaml
charts/influxdb3-clustered/templates/kubit.yml

Prior to this PR setting `Values.kubitSingleNamespace` to `false` would
cause it to watch only a single namespace, which seems to be the `kubit`
namespace itself. The reason it ends up watching the `kubit` namespace
can be seen in the deployment's namespace setting:
```
namespace: {{if .Values.kubitSingleNamespace}}{{.Values.namespaceOverride | default .Release.Namespace}}{{else}}kubit{{end}}
```
(ie we hit the `else` branch in this logic when `kubitSingleNamespace` is false)

fix(templates/kubit): logic inversion on kubitSingleNamespace

---

charts/influxdb3-clustered/Chart.yaml
charts/influxdb3-clustered/templates/app-instance.yml

key getting the following error when adding a list for `image.overrides`
`Error: YAML parse error on influxdb3-clustered/templates/app-instance.yml: error converting YAML to JSON: yaml: line 19: did not find expected ',' or ']'`
Added with block to resolve issue for image overrides.

fix: image override error when passing list

---

charts/telegraf/Chart.yaml
charts/telegraf/templates/deployment.yaml
charts/telegraf/values.yaml

Support define telegraf container ports for success as  [victoria metrics agent](https://github.com/VictoriaMetrics/helm-charts/tree/4040c7e6f9a134972535fb1fdf9c973a2dfb53be/charts/victoria-metrics-agent) scrape targets.
- default drop rule in [kubernetes-service-endpoints-job](https://github.com/VictoriaMetrics/helm-charts/blob/4040c7e6f9a134972535fb1fdf9c973a2dfb53be/charts/victoria-metrics-agent/values.yaml#L422-L426)

feat: support define telegraf container ports

---

charts/influxdb-enterprise/Chart.yaml
charts/influxdb-enterprise/templates/data-statefulset.yaml
charts/influxdb-enterprise/templates/meta-statefulset.yaml

- typo when creating the initial PR
- Need to set up the end before the liveness probe or else it gets caught up in the https enabled false and you cannot set it

fix(edge): need to set end block for http

---

.github/workflows/helm-charts-release.yaml
.github/workflows/helm-charts-test.yaml

This is an attempt to fix the recent workflow errors complaining about python v3.7 not being available for Ubuntu 24.04. While being at it, this PR bumps all actions to their latest available version.

chore: Bump github action versions

---

charts/influxdb3-clustered/Chart.yaml

Updates helm charts for new clustered release: https://github.com/influxdata/k8s-idpe/pull/54346.

chore: helm chart clustered update

---

.github/workflows/helm-charts-test.yaml
charts/influxdb3-clustered/Chart.yaml
charts/influxdb3-clustered/templates/app-instance.yml
charts/influxdb3-clustered/values.yaml

Closes https://github.com/influxdata/EAR/issues/5836
This adds the `observability.ServiceMonitor` keys and changes `hostingEnvironment.eks` to `hostingEnvironment.aws`.

chore(influxdb3-clustered): update clustered helm chart

---

charts/influxdb3-clustered/Chart.yaml

Updates the clustered helm charts to the `20250508-1719206` release

chore: update chart for 20250508-1719206 release
